WITH HISTORICO_PARTIDAS_TECNICOS AS (
    SELECT
        p.ID_PARTIDA,
        p.ID_TECNICO_HOME AS ID_TECNICO,
        t.NOME_TECNICO,
        t.PAIS_ORIGEM AS PAIS_TECNICO,
        s.NOME_SELECAO AS PAIS_SELECAO,
        p.GOLS_HOME AS GOLS_PRO
    FROM TB_PARTIDA p
    INNER JOIN TB_TECNICO t ON p.ID_TECNICO_HOME = t.ID_TECNICO
    INNER JOIN TB_SELECAO s ON p.ID_SELECAO_HOME = s.ID_SELECAO

    UNION ALL

    SELECT
        p.ID_PARTIDA,
        p.ID_TECNICO_AWAY AS ID_TECNICO,
        t.NOME_TECNICO,
        t.PAIS_ORIGEM AS PAIS_TECNICO,
        s.NOME_SELECAO AS PAIS_SELECAO,
        p.GOLS_AWAY AS GOLS_PRO
    FROM TB_PARTIDA p
    INNER JOIN TB_TECNICO t ON p.ID_TECNICO_AWAY = t.ID_TECNICO
    INNER JOIN TB_SELECAO s ON p.ID_SELECAO_AWAY = s.ID_SELECAO
),
CLASSIFICACAO_TECNICOS AS (
    SELECT
        GOLS_PRO,
        CASE
            WHEN PAIS_TECNICO = PAIS_SELECAO THEN 'Técnico Nacional'
            ELSE 'Técnico Estrangeiro'
        END AS TIPO_COMANDO
    FROM HISTORICO_PARTIDAS_TECNICOS
)
SELECT
    TIPO_COMANDO,
    COUNT(*) AS TOTAL_PARTIDAS_CONDUZIDAS,
    SUM(GOLS_PRO) AS TOTAL_GOLS_PRO,
    ROUND(AVG(GOLS_PRO), 2) AS MEDIA_GOLS_PRO,
    MAX(GOLS_PRO) AS MAX_GOLS_NUM_UNICO_JOGO,
    MIN(GOLS_PRO) AS MIN_GOLS_NUM_UNICO_JOGO
FROM CLASSIFICACAO_TECNICOS
GROUP BY TIPO_COMANDO
ORDER BY MEDIA_GOLS_PRO DESC;
