SELECT
    S.NOME_SELECAO AS Selecao,
    COUNT(E.ID_EVENTO) AS Gols_Mata_Mata_Ate_Min_10
FROM TB_EVENTO_JOGADOR E
INNER JOIN TB_PARTIDA_JOGADOR PJ ON E.ID_PARTIDA = PJ.ID_PARTIDA AND E.ID_JOGADOR = PJ.ID_JOGADOR
INNER JOIN TB_SELECAO S ON PJ.ID_SELECAO = S.ID_SELECAO
INNER JOIN TB_PARTIDA P ON E.ID_PARTIDA = P.ID_PARTIDA
WHERE P.FASE != 'Group Stage'
  AND E.TIPO_EVENTO LIKE 'G%'
  AND E.MINUTO <= 10
GROUP BY S.NOME_SELECAO
HAVING COUNT(E.ID_EVENTO) > 0
ORDER BY Gols_Mata_Mata_Ate_Min_10 DESC, Selecao ASC
LIMIT 10;
