SELECT
    J.NOME_JOGADOR AS Jogador,
    S.NOME_SELECAO AS Selecao_Jogador,
    P.FASE AS Fase_da_Partida,
    P.GOLS_HOME || ' x ' || P.GOLS_AWAY AS Placar_Final,
    E.MINUTO AS Minuto_do_Gol
FROM TB_EVENTO_JOGADOR E
INNER JOIN TB_PARTIDA_JOGADOR PJ ON E.ID_PARTIDA = PJ.ID_PARTIDA AND E.ID_JOGADOR = PJ.ID_JOGADOR
INNER JOIN TB_JOGADOR J ON PJ.ID_JOGADOR = J.ID_JOGADOR
INNER JOIN TB_SELECAO S ON PJ.ID_SELECAO = S.ID_SELECAO
INNER JOIN TB_PARTIDA P ON E.ID_PARTIDA = P.ID_PARTIDA
WHERE E.TIPO_EVENTO LIKE 'G%'
  AND ABS(P.GOLS_HOME - P.GOLS_AWAY) = 1
  AND E.MINUTO > 85
GROUP BY P.ID_PARTIDA, J.ID_JOGADOR, E.MINUTO
ORDER BY E.MINUTO DESC, Jogador ASC
LIMIT 15
