WITH PodioPorAno AS (
    SELECT ANO_COPA, ID_CAMPEAO AS ID_SELECAO, '1º Lugar (Campeão)' AS POSICAO FROM TB_COPA
    UNION ALL
    SELECT ANO_COPA, ID_VICE AS ID_SELECAO, '2º Lugar (Vice)' AS POSICAO FROM TB_COPA
    UNION ALL
    SELECT ANO_COPA, ID_TERCEIRO AS ID_SELECAO, '3º Lugar' AS POSICAO FROM TB_COPA
    UNION ALL
    SELECT ANO_COPA, ID_QUARTO AS ID_SELECAO, '4º Lugar' AS POSICAO FROM TB_COPA
)
SELECT
    S.NOME_SELECAO AS [Seleção],
    P1.POSICAO AS [Posição Repetida],
    P1.ANO_COPA AS [Ano Inicial],
    P2.ANO_COPA AS [Ano Consecutivo]
FROM PodioPorAno P1
INNER JOIN PodioPorAno P2 ON P1.ID_SELECAO = P2.ID_SELECAO
                         AND P1.POSICAO = P2.POSICAO
                         AND P2.ANO_COPA = P1.ANO_COPA + 4
INNER JOIN TB_SELECAO S ON P1.ID_SELECAO = S.ID_SELECAO
ORDER BY P1.ANO_COPA DESC;

