SELECT
    c.ANO_COPA,
    s.NOME_SELECAO AS SELECAO_CAMPEA,
    COUNT(p.ID_PARTIDA) AS TOTAL_PARTIDAS_JOGADAS,
    SUM(CASE WHEN p.ID_SELECAO_HOME = c.ID_CAMPEAO THEN p.GOLS_HOME ELSE p.GOLS_AWAY END) AS TOTAL_GOLS_MARCADOS,
    ROUND(AVG(CASE WHEN p.ID_SELECAO_HOME = c.ID_CAMPEAO THEN p.GOLS_HOME ELSE p.GOLS_AWAY END), 2) AS MEDIA_GOLS_POR_PARTIDA
FROM TB_COPA c
INNER JOIN TB_SELECAO s ON c.ID_CAMPEAO = s.ID_SELECAO
INNER JOIN TB_PARTIDA p ON c.ANO_COPA = p.ANO_COPA AND (p.ID_SELECAO_HOME = c.ID_CAMPEAO OR p.ID_SELECAO_AWAY = c.ID_CAMPEAO)
GROUP BY c.ANO_COPA, s.NOME_SELECAO
HAVING TOTAL_PARTIDAS_JOGADAS > 0
ORDER BY MEDIA_GOLS_POR_PARTIDA ASC
LIMIT 1;
