WITH GolsDetalhados AS (
    SELECT ANO_COPA, ID_SELECAO_HOME AS ID_SELECAO, GOLS_HOME AS GOLS FROM TB_PARTIDA
    UNION ALL
    SELECT ANO_COPA, ID_SELECAO_AWAY AS ID_SELECAO, GOLS_AWAY AS GOLS FROM TB_PARTIDA
),
GolsPorSelecao AS (
    SELECT GD.ANO_COPA, GD.ID_SELECAO, S.NOME_SELECAO, SUM(GD.GOLS) AS TOTAL_GOLS_MARCADOS
    FROM GolsDetalhados GD
    INNER JOIN TB_SELECAO S ON S.ID_SELECAO = GD.ID_SELECAO
    GROUP BY GD.ANO_COPA, GD.ID_SELECAO, S.NOME_SELECAO
),
MelhoresAtaques AS (
    SELECT G1.ANO_COPA, G1.ID_SELECAO, G1.NOME_SELECAO, G1.TOTAL_GOLS_MARCADOS
    FROM GolsPorSelecao G1
    WHERE G1.TOTAL_GOLS_MARCADOS = (SELECT MAX(G2.TOTAL_GOLS_MARCADOS) FROM GolsPorSelecao G2 WHERE G2.ANO_COPA = G1.ANO_COPA)
)
SELECT
    MA.ANO_COPA AS "Ano da Copa",
    C.PAIS_SEDE AS "País Sede",
    MA.NOME_SELECAO AS "Melhor Ataque",
    MA.TOTAL_GOLS_MARCADOS AS "Total Gols"
FROM MelhoresAtaques MA
INNER JOIN TB_COPA C ON MA.ANO_COPA = C.ANO_COPA
LEFT JOIN TB_COPA C1 ON MA.ANO_COPA = C1.ANO_COPA AND MA.ID_SELECAO = C1.ID_CAMPEAO
LEFT JOIN TB_COPA C2 ON MA.ANO_COPA = C2.ANO_COPA AND MA.ID_SELECAO = C2.ID_VICE
LEFT JOIN TB_COPA C3 ON MA.ANO_COPA = C3.ANO_COPA AND MA.ID_SELECAO = C3.ID_TERCEIRO
LEFT JOIN TB_COPA C4 ON MA.ANO_COPA = C4.ANO_COPA AND MA.ID_SELECAO = C4.ID_QUARTO
WHERE C1.ANO_COPA IS NULL AND C2.ANO_COPA IS NULL AND C3.ANO_COPA IS NULL AND C4.ANO_COPA IS NULL
ORDER BY MA.ANO_COPA DESC;
