WITH GolsDetalhados AS (
    SELECT ANO_COPA, ID_SELECAO_HOME AS ID_SELECAO, GOLS_HOME AS GOLS FROM TB_PARTIDA
    UNION ALL
    SELECT ANO_COPA, ID_SELECAO_AWAY AS ID_SELECAO, GOLS_AWAY AS GOLS FROM TB_PARTIDA
),
GolsPorSelecao AS (
    SELECT GD.ANO_COPA, GD.ID_SELECAO, S.NOME_SELECAO, SUM(GD.GOLS) AS TOTAL_GOLS
    FROM GolsDetalhados GD
    INNER JOIN TB_SELECAO S ON S.ID_SELECAO = GD.ID_SELECAO
    GROUP BY GD.ANO_COPA, GD.ID_SELECAO, S.NOME_SELECAO
),
MelhoresAtaques AS (
    SELECT G1.ANO_COPA, G1.NOME_SELECAO AS MELHOR_ATAQUE, G1.TOTAL_GOLS
    FROM GolsPorSelecao G1
    WHERE G1.TOTAL_GOLS = (SELECT MAX(G2.TOTAL_GOLS) FROM GolsPorSelecao G2 WHERE G2.ANO_COPA = G1.ANO_COPA)
)
SELECT
    MA.ANO_COPA AS "Ano",
    MA.MELHOR_ATAQUE AS "Melhor Ataque",
    MA.TOTAL_GOLS AS "Gols",
    S1.NOME_SELECAO AS "Campeão",
    S2.NOME_SELECAO AS "Vice",
    S3.NOME_SELECAO AS "3º Colocado",
    S4.NOME_SELECAO AS "4º Colocado"
FROM MelhoresAtaques MA
INNER JOIN TB_COPA C ON MA.ANO_COPA = C.ANO_COPA
INNER JOIN TB_SELECAO S1 ON C.ID_CAMPEAO = S1.ID_SELECAO
INNER JOIN TB_SELECAO S2 ON C.ID_VICE = S2.ID_SELECAO
LEFT JOIN TB_SELECAO S3 ON C.ID_TERCEIRO = S3.ID_SELECAO
LEFT JOIN TB_SELECAO S4 ON C.ID_QUARTO = S4.ID_SELECAO
ORDER BY MA.ANO_COPA ASC;
