WITH G4_Por_Ano AS (
    SELECT ANO_COPA, ID_CAMPEAO AS ID_SELECAO, 1 AS EH_CAMPEAO FROM TB_COPA
    UNION ALL
    SELECT ANO_COPA, ID_VICE AS ID_SELECAO, 0 AS EH_CAMPEAO FROM TB_COPA
    UNION ALL
    SELECT ANO_COPA, ID_TERCEIRO AS ID_SELECAO, 0 AS EH_CAMPEAO FROM TB_COPA
    UNION ALL
    SELECT ANO_COPA, ID_QUARTO AS ID_SELECAO, 0 AS EH_CAMPEAO FROM TB_COPA
),
Estatistica_G4 AS (
    SELECT
        ID_SELECAO,
        COUNT(ANO_COPA) AS TOTAL_G4,
        SUM(EH_CAMPEAO) AS TOTAL_TITULOS,
        (SUM(EH_CAMPEAO) * 1.0 / COUNT(ANO_COPA)) AS TAXA_CONVERSAO
    FROM G4_Por_Ano
    GROUP BY ID_SELECAO
)
SELECT
    S.NOME_SELECAO AS "Seleção",
    E.TOTAL_G4 AS "Aparições no G4 (Semi/Final)",
    E.TOTAL_TITULOS AS "Total de Títulos",
    ROUND(E.TAXA_CONVERSAO * 100, 2) || '%' AS "Taxa de Conversão em Títulos"
FROM Estatistica_G4 E
INNER JOIN TB_SELECAO S ON E.ID_SELECAO = S.ID_SELECAO
WHERE E.TOTAL_G4 > 0
ORDER BY E.TOTAL_G4 DESC, E.TAXA_CONVERSAO ASC
LIMIT 5;
