WITH MAPA_PARTIDAS_TECNICOS AS (
    SELECT p.ID_PARTIDA, p.ID_TECNICO_HOME AS ID_TECNICO, p.ID_SELECAO_HOME AS ID_SELECAO FROM TB_PARTIDA p
    UNION ALL
    SELECT p.ID_PARTIDA, p.ID_TECNICO_AWAY AS ID_TECNICO, p.ID_SELECAO_AWAY AS ID_SELECAO FROM TB_PARTIDA p
)
SELECT
    t.NOME_TECNICO,
    t.PAIS_ORIGEM AS NACIONALIDADE_TECNICO,
    COUNT(DISTINCT m.ID_SELECAO) AS QTD_SELECOES_DIFERENTES,
    COUNT(m.ID_PARTIDA) AS TOTAL_PARTIDAS_ACUMULADAS
FROM MAPA_PARTIDAS_TECNICOS m
INNER JOIN TB_TECNICO t ON m.ID_TECNICO = t.ID_TECNICO
GROUP BY t.ID_TECNICO, t.NOME_TECNICO, t.PAIS_ORIGEM
HAVING QTD_SELECOES_DIFERENTES >= 2
ORDER BY QTD_SELECOES_DIFERENTES DESC, TOTAL_PARTIDAS_ACUMULADAS DESC
LIMIT 10
