WITH PrimeiraPartidaTecnico AS (
    SELECT ID_TECNICO, MIN(DATA_HORA) AS DATA_ESTREIA
    FROM (
        SELECT ID_TECNICO_HOME AS ID_TECNICO, DATA_HORA FROM TB_PARTIDA
        UNION
        SELECT ID_TECNICO_AWAY AS ID_TECNICO, DATA_HORA FROM TB_PARTIDA
    )
    GROUP BY ID_TECNICO
)
SELECT
    T.NOME_TECNICO,
    T.PAIS_ORIGEM AS NACIONALIDADE_TECNICO,
    P.ANO_COPA,
    P.DATA_HORA AS DATA_PARTIDA,
    S_HOME.NOME_SELECAO AS TIME_CASA,
    P.GOLS_HOME,
    P.GOLS_AWAY,
    S_AWAY.NOME_SELECAO AS TIME_VISITANTE,
    ABS(P.GOLS_HOME - P.GOLS_AWAY) AS DIFERENCA_GOLS
FROM PrimeiraPartidaTecnico PPT
INNER JOIN TB_TECNICO T ON PPT.ID_TECNICO = T.ID_TECNICO
INNER JOIN TB_PARTIDA P ON (PPT.ID_TECNICO = P.ID_TECNICO_HOME OR PPT.ID_TECNICO = P.ID_TECNICO_AWAY) AND PPT.DATA_ESTREIA = P.DATA_HORA
INNER JOIN TB_SELECAO S_HOME ON P.ID_SELECAO_HOME = S_HOME.ID_SELECAO
INNER JOIN TB_SELECAO S_AWAY ON P.ID_SELECAO_AWAY = S_AWAY.ID_SELECAO
WHERE (PPT.ID_TECNICO = P.ID_TECNICO_HOME AND (P.GOLS_HOME - P.GOLS_AWAY) >= 3)
   OR (PPT.ID_TECNICO = P.ID_TECNICO_AWAY AND (P.GOLS_AWAY - P.GOLS_HOME) >= 3)
ORDER BY P.ANO_COPA DESC, DIFERENCA_GOLS DESC
LIMIT 10;
