SELECT
    E.NOME_ESTADIO,
    C.NOME_CIDADE,
    COUNT(P.ID_PARTIDA) AS TOTAL_JOGOS_DECISIVOS,
    ROUND(AVG(P.GOLS_HOME + P.GOLS_AWAY), 2) AS MEDIA_GOLS
FROM TB_PARTIDA P
INNER JOIN TB_ESTADIO E ON P.ID_ESTADIO = E.ID_ESTADIO
INNER JOIN TB_CIDADE C ON E.ID_CIDADE = C.ID_CIDADE
WHERE P.FASE IN ('Semifinal', 'Final')
GROUP BY E.ID_ESTADIO, E.NOME_ESTADIO, C.NOME_CIDADE
HAVING COUNT(P.ID_PARTIDA) >= 2
ORDER BY MEDIA_GOLS DESC, TOTAL_JOGOS_DECISIVOS DESC
LIMIT 10
