SELECT
    C.NOME_CIDADE AS Cidade,
    COUNT(DISTINCT E.ID_ESTADIO) AS Qtd_Estadios_Diferentes,
    COUNT(P.ID_PARTIDA) AS Total_Partidas_Sediadas,
    MIN(P.ANO_COPA) AS Primeira_Copa_Na_Cidade,
    MAX(P.ANO_COPA) AS Ultima_Copa_Na_Cidade
FROM TB_CIDADE C
INNER JOIN TB_ESTADIO E ON C.ID_CIDADE = E.ID_CIDADE
INNER JOIN TB_PARTIDA P ON E.ID_ESTADIO = P.ID_ESTADIO
GROUP BY C.ID_CIDADE, C.NOME_CIDADE
HAVING COUNT(DISTINCT E.ID_ESTADIO) > 1
ORDER BY Total_Partidas_Sediadas DESC, Qtd_Estadios_Diferentes DESC
LIMIT 10
