SELECT
    P.ANO_COPA AS [Ano da Copa],
    P.FASE AS [Fase],
    S_HOME.NOME_SELECAO AS [Seleção Mandante],
    P.GOLS_HOME AS [Placar Mandante],
    P.GOLS_AWAY AS [Placar Visitante],
    S_AWAY.NOME_SELECAO AS [Seleção Visitante],
    MIN(P.PUBLICO) AS [Público]
FROM TB_PARTIDA P
INNER JOIN TB_SELECAO S_HOME ON P.ID_SELECAO_HOME = S_HOME.ID_SELECAO
INNER JOIN TB_SELECAO S_AWAY ON P.ID_SELECAO_AWAY = S_AWAY.ID_SELECAO
WHERE P.FASE NOT LIKE '%Grupo%'
  AND P.FASE NOT LIKE '%Group%'
  AND P.FASE NOT LIKE '%Primeira%'
  AND P.PUBLICO IS NOT NULL
GROUP BY P.ID_PARTIDA, P.ANO_COPA, P.FASE, S_HOME.NOME_SELECAO, S_AWAY.NOME_SELECAO
HAVING [Público] > 0
ORDER BY [Público] ASC
LIMIT 5;
