--- 04-06-2026 14:39:01 SQLite
SELECT
    j.NOME_JOGADOR,
    s.NOME_SELECAO,
    COUNT(e.ID_EVENTO) AS TOTAL_GOLS_RESERVA
FROM TB_EVENTO_JOGADOR e
INNER JOIN TB_PARTIDA_JOGADOR pj ON e.ID_PARTIDA = pj.ID_PARTIDA AND e.ID_JOGADOR = pj.ID_JOGADOR
INNER JOIN TB_JOGADOR j ON pj.ID_JOGADOR = j.ID_JOGADOR
INNER JOIN TB_SELECAO s ON pj.ID_SELECAO = s.ID_SELECAO
WHERE pj.ESCALACAO_INICIAL = 'S'
  AND (e.TIPO_EVENTO LIKE '%Goal%' OR e.TIPO_EVENTO LIKE '%G%')
GROUP BY j.ID_JOGADOR, j.NOME_JOGADOR, s.NOME_SELECAO
HAVING TOTAL_GOLS_RESERVA > 0
ORDER BY TOTAL_GOLS_RESERVA DESC, j.NOME_JOGADOR ASC
LIMIT 10
