SELECT
    CASE
        WHEN pj.POSICAO = 'GK' THEN 'Goleiros'
        WHEN pj.POSICAO = 'GLC' THEN 'Defensores / Laterais'
        WHEN pj.POSICAO = 'C' THEN 'Meias / Atacantes (Capitães)'
        ELSE 'Setor Não Informado'
    END AS SETOR_CAMPO,
    COUNT(ej.ID_EVENTO) AS TOTAL_EVENTOS_ANALISADOS,
    ROUND(AVG(ej.MINUTO), 2) AS MEDIA_MINUTO_EVENTO
FROM TB_EVENTO_JOGADOR ej
INNER JOIN TB_PARTIDA_JOGADOR pj ON ej.ID_PARTIDA = pj.ID_PARTIDA AND ej.ID_JOGADOR = pj.ID_JOGADOR
WHERE ej.TIPO_EVENTO LIKE 'G%'
   OR ej.TIPO_EVENTO LIKE 'Y%'
   OR ej.TIPO_EVENTO LIKE 'R%'
GROUP BY SETOR_CAMPO
HAVING TOTAL_EVENTOS_ANALISADOS > 5
ORDER BY MEDIA_MINUTO_EVENTO DESC;
