SELECT
    pj.NUMERO_CAMISA,
    COUNT(DISTINCT pj.ID_PARTIDA || '-' || pj.ID_JOGADOR) AS TOTAL_ATLETAS_CONVOCADOS,
    SUM(CASE WHEN ej.TIPO_EVENTO LIKE 'G%' THEN 1 ELSE 0 END) AS TOTAL_GOLS,
    SUM(CASE WHEN ej.TIPO_EVENTO LIKE 'Y%' OR ej.TIPO_EVENTO LIKE 'R%' THEN 1 ELSE 0 END) AS TOTAL_CARTOES
FROM TB_PARTIDA_JOGADOR pj
INNER JOIN TB_EVENTO_JOGADOR ej ON pj.ID_PARTIDA = ej.ID_PARTIDA AND pj.ID_JOGADOR = ej.ID_JOGADOR
WHERE pj.NUMERO_CAMISA IS NOT NULL AND pj.NUMERO_CAMISA > 0
GROUP BY pj.NUMERO_CAMISA
HAVING TOTAL_CARTOES > TOTAL_GOLS
ORDER BY TOTAL_CARTOES DESC
LIMIT 10;
